#!/bin/bash

# FastReactCMS - Automated PostgreSQL Setup Script
# This script automatically sets up PostgreSQL database for FastReactCMS

set -e

echo "🚀 FastReactCMS - PostgreSQL Setup Script"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
  echo "❌ Please do not run this script as root"
  exit 1
fi

# Configuration
DB_NAME="${DB_NAME:-fastreactcms}"
DB_USER="${DB_USER:-fastreactcms_user}"
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -base64 32 | tr -d /=+)}"  # Generate secure password if not provided

echo "📋 Configuration:"
echo "   Database Name: $DB_NAME"
echo "   Database User: $DB_USER"
echo "   Password: [HIDDEN - will be saved to .env]"
echo ""

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo "📦 PostgreSQL not found. Installing..."
    sudo apt update
    sudo apt install -y postgresql postgresql-contrib
    echo "✅ PostgreSQL installed"
else
    echo "✅ PostgreSQL already installed"
fi

# Start PostgreSQL service
echo "🔄 Starting PostgreSQL service..."
sudo systemctl start postgresql
sudo systemctl enable postgresql
echo "✅ PostgreSQL service started"

# Create database and user
echo "🗄️  Creating database and user..."
sudo -u postgres psql <<EOF
-- Drop database if exists (for clean setup)
DROP DATABASE IF EXISTS $DB_NAME;
DROP USER IF EXISTS $DB_USER;

-- Create database and user
CREATE DATABASE $DB_NAME;
CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;

-- Connect to database and grant schema permissions (PostgreSQL 15+)
\c $DB_NAME
GRANT ALL ON SCHEMA public TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $DB_USER;

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Exit
\q
EOF
echo "✅ Database and user created"

# Update backend .env file
ENV_FILE="backend/.env"
ENV_EXAMPLE="backend/.env.example"

if [ ! -f "$ENV_FILE" ]; then
    if [ -f "$ENV_EXAMPLE" ]; then
        echo "📝 Creating .env file from .env.example..."
        cp "$ENV_EXAMPLE" "$ENV_FILE"
    else
        echo "📝 Creating new .env file..."
        touch "$ENV_FILE"
    fi
fi

# Generate secrets
SECRET_KEY=$(openssl rand -hex 32)
CSRF_SECRET_KEY=$(openssl rand -hex 32)

# Update .env file with database credentials
echo "📝 Updating .env file..."
cat > "$ENV_FILE" <<EOF
# Database Configuration (Auto-generated by setup-postgres.sh)
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@localhost/$DB_NAME

# Security Keys (Auto-generated)
SECRET_KEY=$SECRET_KEY
CSRF_SECRET_KEY=$CSRF_SECRET_KEY

# Admin Credentials (CHANGE THESE!)
ADMIN_EMAIL=admin@yourdomain.com
ADMIN_PASSWORD=admin123

# Cookie Security
COOKIE_SECURE=false
COOKIE_SAMESITE=lax
ENVIRONMENT=development

# CORS Origins
CORS_ORIGINS=["http://localhost:5173"]

# Optional: Upload Settings
MAX_UPLOAD_SIZE=10485760
UPLOAD_DIR=static/uploads
EOF

echo "✅ .env file updated"

# Test database connection
echo "🔍 Testing database connection..."
if PGPASSWORD=$DB_PASSWORD psql -h localhost -U $DB_USER -d $DB_NAME -c "SELECT version();" > /dev/null 2>&1; then
    echo "✅ Database connection successful!"
else
    echo "❌ Database connection failed"
    exit 1
fi

# Run database migrations
if [ -f "backend/alembic.ini" ]; then
    echo "🔄 Running database migrations..."
    cd backend

    # Activate virtual environment if exists
    if [ -d "venv" ]; then
        source venv/bin/activate
    fi

    # Run migrations
    alembic upgrade head || echo "⚠️  Migrations failed (run manually: cd backend && alembic upgrade head)"

    cd ..
    echo "✅ Database migrations complete"
else
    echo "⚠️  alembic.ini not found. Skipping migrations."
fi

echo ""
echo "=========================================="
echo "✅ PostgreSQL setup complete!"
echo ""
echo "📋 Database Details:"
echo "   Database: $DB_NAME"
echo "   Username: $DB_USER"
echo "   Password: $DB_PASSWORD"
echo "   Connection: postgresql://$DB_USER:$DB_PASSWORD@localhost/$DB_NAME"
echo ""
echo "📝 Next Steps:"
echo "   1. Update admin credentials in backend/.env"
echo "   2. Run seed scripts:"
echo "      cd backend"
echo "      source venv/bin/activate  # (if using venv)"
echo "      python scripts/create_admin.py"
echo "      python scripts/seed_categories.py"
echo "      python scripts/seed_navigation_theme.py"
echo "      python scripts/seed_pages.py"
echo "   3. Start the backend:"
echo "      uvicorn app.main:app --reload --host 0.0.0.0 --port 8100"
echo ""
echo "⚠️  IMPORTANT: Save your database password!"
echo "   Password has been saved to backend/.env"
echo "=========================================="
